version: '3'
services: 
  calendario-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: calendario-server
    env_file: .env
    environment: 
      - SERVER_PORT=$SERVER_PORT
    ports:
    - 8080:$SERVER_PORT
    volumes:
    - node_modules:/usr/src/app/node_modules
    networks: 
    - calendario-network
networks: 
  calendario-network:
volumes: 
  node_modules:
