version: '3'
services: 
  calendario-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: calendario-server
    env_file: .env
    environment: 
      - MONGO_HOSTNAME=calendariodb
      - MONGO_PORT=27017
    ports:
    - 8080:$SERVER_PORT
    volumes:
    - node_modules:/usr/src/app/node_modules
    networks: 
    - calendario-network
    depends_on: 
    - calendariodb
  calendariodb:
    image: mongo:4.1.8-xenial
    container_name: calendariodb
    env_file: .env
    volumes:
      - dbdata:/data/db
    networks:
      - calendario-network
networks: 
  calendario-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
